@startuml tables

entity order as "order\nオーダー" {
  オーダーID :int [PK]
  --
  顧客ID :int [FK]
  合計皿数 :int
  合計金額（税抜） :int
  合計金額（税込み） :int
  消費税 :int
  決済ステータス :bool
  注文日時 :datetime
  支払い日時 :datetime
}

entity order_details as "order_details\nオーダー詳細" {
  オーダーID :int [PK]
  メニューID :int [PK]
  サイズ種別 :int [PK]
  --
  ワサビ抜き個数 :int
  皿数 :int
  注文日時 :datetime
}

entity customer as "customer\n顧客" {
  顧客ID :int [PK]
  --
  顧客名 :varchar
  電話番号 :int
}

entity menu as "menu\nメニュー" {
  メニューID :int [PK]
  --
  メニュー名 :varchar
  値段 :int
  メニュー種別ID :int
}

entity menu_types as "menu_types\nメニュー種別" {
  メニュー種別ID :int [PK]
  --
  メニュー種別名 :varchar
}



@enduml